### ISSUE TITLE
found 1 low severity vulnerability   run `npm audit fix` to fix them, or `npm audit` for details. I dont know why this occurs everytime.

### ISSUE THREAD

**Issue by ankushgod** [microsoft/vscode-npm-scripts#124]
PS C:\Users\ACER\Desktop\MyVegoAdmin> npx create-react-app vego-admin

Creating a new React app in C:\Users\ACER\Desktop\MyVegoAdmin\vego-admin.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

> core-js@2.6.11 postinstall C:\Users\ACER\Desktop\MyVegoAdmin\vego-admin\node_modules\babel-runtime\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@3.6.5 postinstall C:\Users\ACER\Desktop\MyVegoAdmin\vego-admin\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js-pure@3.6.5 postinstall C:\Users\ACER\Desktop\MyVegoAdmin\vego-admin\node_modules\core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

+ cra-template@1.0.3
+ react-scripts@3.4.1
+ react@16.13.1
+ react-dom@16.13.1
added 1626 packages from 751 contributors and audited 1630 packages in 422.406s

59 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by ponkuma123** [comment]
I have same problem.......how to fix it

**Comment by proxxz** [comment]
That's not an error, but is core functionality of npm.  The message occurs every time because the vulnerability hasn't been fixed.  The message tells you to run `npm audit fix` to try and fix the vulnerability.  Sometimes npm is not able to fix it since the problem lies in a dependency.

In short, these messages are warnings and not errors.  They won't affect the results of your build.
