### ISSUE TITLE
Keyboard Shortcut conflicts with Open Recent

### ISSUE THREAD

**Issue by Dante-101** [Microsoft/vscode-npm-scripts#42]
Ctrl+R is now assigned to Open recent in VS Code. Installing this extension disables the Open Recent. Can we change the shortcuts to something else?

**Comment by egamma** [comment]
It is very difficult to come up with free keybinding short cuts, so the current approach is to defer this to the user, sorry. see https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by patrickgreenwell** [comment]
I'm going to further boost this as an issue. This is an officially supported microsoft package for vscode, the fact that conflicting keybindings are an issue is a big one.  The problem is that the two stroke key binding of `Ctrl+R <second-stroke>` prevents the single stroke keybinding from actually executing.

Either remap the open recent when this extension is installed to add a second stroke for it or open an issue with VSCode core team to resolve the second stroke preventing single stroke keys.

![image](https://user-images.githubusercontent.com/5296581/52132377-01509780-260d-11e9-840b-af363ee05dad.png)

**Comment by egamma** [comment]
@patrickgreenwell pls notice that most features of this extension have been replaced with NPM script running support that is now bundled with VS Code (see https://github.com/Microsoft/vscode/blob/master/extensions/npm/README.md).

**Comment by patrickgreenwell** [comment]
@egamma Good to know, I suppose that's the price I pay for not doing an audit of my extensions periodically 👍

**Comment by tayambamwanza** [comment]
@egamma Could you please put an additional note at the top of the extension description about this?

e.g. 'This extension overwrites some default keybindings of vs code, see the last section for more info.'.
