### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by thegoldengideon** [Microsoft/vscode-npm-scripts#51]
please i am using vscode, i tried to install vscode by using

npm install, it said 
bash code not found

**Comment by egamma** [comment]
@thegoldengideon the repository is about an npm extension and your problem is not related to this extension.

If you have problems installing VS Code then please file an issue against vscode with detailed steps to reproduce. Please notice that you cannot install VS Code using ´npm install code´ you have to download it from here https://code.visualstudio.com/Download.

**Comment by thegoldengideon** [comment]
@egamma 
I have installed vscode, and I had no issue with it.
I want the nodes modules folder to appear in my laravel app folder...
so I used the command in bash to want to install npm...

**Comment by egamma** [comment]
Great that installing vscode worked for you. So the issue about how to use npm in general and has nothing to do with VS Code. In this case I suggest to ask the question on Stack Overflow or look into the documentation for how to install npm on your platform.

**Comment by thegoldengideon** [comment]
owk  thanks, please @egamma i will appreciate a link to the solution.
King Regards,
Gideon
